/* Included in: main */
Char *keyname[256] =	/* key names for LOAD and UNLOAD commands */
{
	"gold-A","gold-B","gold-C","gold-D",
	"gold-E","gold-F","gold-G","gold-H","gold-I","gold-J","gold-K","gold-L",
	"gold-M","gold-N","gold-O","gold-P","gold-Q","gold-R","gold-S","gold-T",
	"gold-U","gold-V","gold-W","gold-X","gold-Y","gold-Z","extra-key-58","extra-key-57",
	"extra-key-56","extra-key-55","extra-key-54","extra-key-53","extra-key-52","extra-key-51","extra-key-50","extra-key-49",
	"extra-key-48","extra-key-47","extra-key-46","extra-key-45","extra-key-44","extra-key-43","extra-key-42","extra-key-41",
	"extra-key-40","extra-key-39","extra-key-38","extra-key-37","extra-key-36","extra-key-35","extra-key-34","extra-key-33",
	"extra-key-32","extra-key-31","extra-key-30","extra-key-29","extra-key-28","extra-key-27","extra-key-26","extra-key-25",
	"extra-key-24","extra-key-23","extra-key-22","extra-key-21","extra-key-20","extra-key-19","extra-key-18","extra-key-17",
	"extra-key-16","extra-key-15","extra-key-14","extra-key-13","extra-key-12","extra-key-11","extra-key-10","extra-key-9",
	"extra-key-8","extra-key-7","extra-key-6","extra-key-5","extra-key-4","extra-key-3","extra-key-2","extra-key-1",
	"scroll-left","scroll-right","mark-spot","return-to-spot","undelete-line","find","window-command","gold-gold",
	"substitute","unselect","undelete-character","undelete-word","replace","word-fill","enter-command","unkill",
	"move-to-top-of-file","move-to-end-of-file","special-insert","delete-to-end-of-line","change-case","open-line",
	"delete-line","find-next","set-copy","gold","enter","select","delete-character","delete-word","append",
	"move-by-section","move-by-page","kill","set-direction-backward","set-direction-forward","move-by-character",
	"move-to-end-of-line","move-by-word","move-by-line","move-left","move-right","move-down","move-up",
	"^@","^A","^B","^C","^D","^E","^F","^G","^H","^I","^J","^K","^L","return","^N","^O",
	"^P","^Q","^R","^S","^T","^U","^V","^W","^X","^Y","^Z","^[","^\\","^]","^^","^_",
	"space","!","\"","#","$","%","&","'","(",")","*","+",",","-",".","/",
	"0","1","2","3","4","5","6","7","8","9",":",";","<","=",">","?",
	"@","A","B","C","D","E","F","G","H","I","J","K","L","M","N","O",
	"P","Q","R","S","T","U","V","W","X","Y","Z","[","\\","]","^","_",
	"`","a","b","c","d","e","f","g","h","i","j","k","l","m","n","o",
	"p","q","r","s","t","u","v","w","x","y","z","{","|","}","~","delete"
};
